version: '3.8'

networks:
  my-network:
    external: true

services:
  redis:
    image: redis:7-alpine
    networks:
      - my-network
    ports:
      - "6379:6379"
    restart: always

  celery_worker:
    build:
      context: .
      dockerfile: services/Dockerfile
    image: flask_celery_worker
    command:
      ["/start-celeryworker", "sh", "-c"]
    env_file:
      - .env
    ports:
      - 6901:6901
    networks:
      - my-network
    depends_on:
      - redis